### ISSUE TITLE
failed omnia install on ubuntu 12.04

### ISSUE THREAD

**Issue by jmichel80** [omnia-md/omnia-md#17]
Hi, 

I'm trying to install omnia in a anaconda 64 bit install on ubuntu 12.04, but i'm having errors downloading packages. See below.

julien@ubuntu:~/software/devel$ conda config --add channels http://conda.binstar.org/omnia
julien@ubuntu:~/software/devel/$ conda install omnia
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment /home/julien/anaconda:

The following packages will be downloaded:

| package | build |
| --- | --- |
| fftw3f-3.3.4 | 2         1.2 MB |
| libgfortran-1.0 | 0         170 KB |
| openblas-0.2.14 | 2         7.0 MB |
| conda-env-2.4.2 | py27_0          24 KB |
| cython-0.23.2 | py27_0         5.5 MB |
| decorator-4.0.2 | py27_0          11 KB |
| joblib-0.8.4 | py27_0          95 KB |
| numpy-1.9.2 | py27_2         8.0 MB |
| openmm-6.3 | py27_0        10.0 MB |
| pdbfixer-1.2 | np19py27_1         180 KB |
| psutil-3.2.0 | py27_0         104 KB |
| python-2.7.10 | 1        12.0 MB |
| pytz-2015.6 | py27_0         173 KB |
| scipy-0.16.0 | np19py27_1        28.2 MB |
| scripttest-1.3 | py27_0          17 KB |
| setuptools-18.1 | py27_0         341 KB |
| wheel-0.26.0 | py27_0          75 KB |
| conda-3.17.0 | py27_0         172 KB |
| jinja2-2.8 | py27_0         263 KB |
| msmtools-1.1 | py27_1         862 KB |
| pip-7.1.2 | py27_0         1.4 MB |
| pymbar-3.0.0.beta2 | np19py27_1         118 KB |
| pytables-3.2.1.1 | np19py27_0         3.4 MB |
| bhmm-0.5.1 | np19py27_0         440 KB |
| pbr-1.3.0 | py27_0          81 KB |
| mdtraj-1.4.2 | np19py27_0        15.1 MB |
| mock-1.3.0 | py27_0          95 KB |
| numpydoc-0.5 | py27_1          53 KB |
| msmbuilder-3.3.0 | np19py27_0         3.5 MB |
| pyemma-2.0.1 | py27_0         566 KB |
| omnia-1.0 | 1           1 KB |

```
------------------------------------------------------------
                                       Total:        98.9 MB
```

The following NEW packages will be INSTALLED:

```
bhmm:        0.5.1-np19py27_0      
fftw3f:      3.3.4-2               
joblib:      0.8.4-py27_0          
libgfortran: 1.0-0                 
mdtraj:      1.4.2-np19py27_0      
msmbuilder:  3.3.0-np19py27_0      
msmtools:    1.1-py27_1            
numpydoc:    0.5-py27_1            
omnia:       1.0-1                 
openblas:    0.2.14-2              
openmm:      6.3-py27_0            
pbr:         1.3.0-py27_0          
pdbfixer:    1.2-np19py27_1        
pyemma:      2.0.1-py27_0          
pymbar:      3.0.0.beta2-np19py27_1
scripttest:  1.3-py27_0            
wheel:       0.26.0-py27_0         
```

The following packages will be UPDATED:

```
conda:       3.14.1-py27_0     --> 3.17.0-py27_0         
conda-env:   2.2.3-py27_0      --> 2.4.2-py27_0          
cython:      0.22.1-py27_0     --> 0.23.2-py27_0         
decorator:   3.4.2-py27_0      --> 4.0.2-py27_0          
jinja2:      2.7.3-py27_1      --> 2.8-py27_0            
mock:        1.0.1-py27_0      --> 1.3.0-py27_0          
numpy:       1.9.2-py27_0      --> 1.9.2-py27_2          
pip:         7.0.3-py27_0      --> 7.1.2-py27_0          
psutil:      2.2.1-py27_0      --> 3.2.0-py27_0          
pytables:    3.2.0-np19py27_0  --> 3.2.1.1-np19py27_0    
python:      2.7.10-0          --> 2.7.10-1              
pytz:        2015.4-py27_0     --> 2015.6-py27_0         
scipy:       0.15.1-np19py27_0 --> 0.16.0-np19py27_1     
setuptools:  17.1.1-py27_0     --> 18.1-py27_0           
```

Proceed ([y]/n)? y

Fetching packages ...
fftw3f-3.3.4-2 100% |#######################################################################################################| Time: 0:00:02 432.22 kB/s
libgfortran-1. 100% |#######################################################################################################| Time: 0:00:00 309.80 kB/s
Error: Could not open u'/home/julien/anaconda/pkgs/openblas-0.2.14-2.tar.bz2.part' for writing ([SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1752)).

Any suggestions to fix the above issue?

**Comment by rmcgibbo** [comment]
Looking at the error message (that it's coming from SSL), this looks like an issue with your network configuration or with the anaconda.org website's SSL configuration. I recommend that you open an issue at https://github.com/conda/conda/issues.

**Comment by jmichel80** [comment]
Switching on a VPN to my Uni before trying again conda install omnia fixed the issue. Thanks !

**Comment by rmcgibbo** [comment]
No problem.
